package process;

import connect.ConnectionToBase;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class UserOperations {

    public void createTables() throws SQLException {
        String createExtension = "CREATE EXTENSION IF NOT EXISTS pgcrypto;";
        String tableUser = "CREATE TABLE users_club(" +
                "id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
                "surname VARCHAR(100)," +
                "first_name VARCHAR(100)," +
                "patronymic VARCHAR(100));";
        String tableUuid = "CREATE TABLE users_uuid( " +
                "uuid UUID PRIMARY KEY DEFAULT gen_random_uuid()," +
                "id_uuid INTEGER NOT NULL," +
                "CONSTRAINT fk_users_deteils " +
                "FOREIGN KEY(id_uuid) REFERENCES users_club(id)" +
                " ON DELETE CASCADE);";
        try (Connection conn = ConnectionToBase.getConnection();
             Statement statement = conn.createStatement()) {
            statement.executeUpdate(createExtension);
            statement.executeUpdate(tableUser);
            statement.executeUpdate(tableUuid);
        }
    }

    public void insert(String surname, String firstName, String patronymic) throws SQLException {
        String insertUser = "INSERT INTO users_club (surname, first_name, patronymic) VALUES (?, ?, ?) RETURNING id";
        String insertUuid = "INSERT INTO users_uuid (id_uuid) VALUES (?)";
        try (Connection conn = ConnectionToBase.getConnection()) {
            conn.setAutoCommit(false);
            try (PreparedStatement psUuid = conn.prepareStatement(insertUuid);
                 PreparedStatement psUser = conn.prepareStatement(insertUser)) {
                psUser.setString(1, surname);
                psUser.setString(2, firstName);
                psUser.setString(3, patronymic);
                try (ResultSet rs = psUser.executeQuery()) {
                    if (!rs.next()) {
                        throw new SQLException("Insert users_club did not return id");
                    }
                    psUuid.setInt(1, rs.getInt("id"));
                    psUuid.executeUpdate();
                    conn.commit();
                } catch (SQLException e) {
                    conn.rollback();
                }
            }
        }
    }

    public void delete(UUID uuid) throws SQLException {
        String sql = "DELETE FROM users_club WHERE uuid = ?;";
        try (Connection conn = ConnectionToBase.getConnection();
             PreparedStatement statement = conn.prepareStatement(sql)) {
            statement.setObject(1, uuid);
            statement.executeUpdate();
        }
    }

    public void updateUser(User user) throws SQLException {
        String sql = "UPDATE users_club SET surname = ?, first_name = ?, patronymic = ? " +
                "WHERE id = (SELECT id_uuid FROM users_uuid WHERE uuid = ?)";
        try (Connection conn = ConnectionToBase.getConnection();
             PreparedStatement statement = conn.prepareStatement(sql)) {
            statement.setString(1, user.getSurname());
            statement.setString(2, user.getFirstName());
            statement.setString(3, user.getPatronymic());
            statement.setObject(4, user.getUuid());
            statement.executeUpdate();
        }
    }

    public void updateQrCode(User user) throws SQLException {
        String sql = "UPDATE users_uuid SET uuid = gen_random_uuid() WHERE uuid = ?";
        try (Connection conn = ConnectionToBase.getConnection();
             PreparedStatement statement = conn.prepareStatement(sql)) {
            statement.setObject(1, user.getUuid());
            statement.executeUpdate();
        }
    }

    public User checkQrCode(UUID uuid) throws SQLException {
        String sqlUserTable = "SELECT uc.surname, uc.first_name, uc.patronymic FROM users_club uc " +
                "JOIN users_uuid uu ON uu.id_uuid = uc.id WHERE uu.uuid = ?";
        try (Connection conn = ConnectionToBase.getConnection();
             PreparedStatement statementTableUser = conn.prepareStatement(sqlUserTable)) {
            statementTableUser.setObject(1, uuid);

            try (ResultSet resultSet = statementTableUser.executeQuery()) {
                if (resultSet.next()) {
                    String surname = resultSet.getString("surname");
                    String firstName = resultSet.getString("first_name");
                    String patronymic = resultSet.getString("patronymic");
                    return new User(uuid, surname, firstName, patronymic);
                } else {
                    return null;
                }
            }
        }
    }

    public List<User> findAll() throws SQLException {
        List<User> users = new ArrayList<>();
        try (Connection conn = ConnectionToBase.getConnection();
             Statement statement = conn.createStatement()) {
            ResultSet resultSet = statement.executeQuery(
                    "SELECT uc.surname, uc.first_name, uc.patronymic, uu.uuid" +
                            "FROM users_club uc" +
                            "JOIN users_uuid uu ON uu.id_uuid = uc.id;");
            while (resultSet.next()) {
                UUID uuid = (UUID) resultSet.getObject("uuid");
                String surname = resultSet.getString("surname");
                String firstName = resultSet.getString("first_name");
                String patronymic = resultSet.getString("patronymic");
                users.add(new User(uuid, surname, firstName, patronymic));
                resultSet.close();
            }
            return users;
        }
    }
}
